# Generated by Django 4.2.1 on 2023-05-29 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VATInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_company_name', models.CharField(max_length=100)),
                ('buyer_company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('measurement_unit', models.CharField(max_length=50)),
                ('price_without_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_tariff', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ersk.vatinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vat_invoices', models.ManyToManyField(to='ersk.vatinvoice')),
            ],
        ),
    ]
